server {
    listen 80;
    server_name _;

    client_max_body_size 2M;

    root /usr/share/nginx/html;
    index index.html;

    # React SPA — toutes les routes renvoient index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API vers Django
    location /api/ {
        proxy_pass http://django:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Proxy media vers Django
    location /media/ {
        proxy_pass http://django:8000/media/;
        proxy_set_header Host $host;
    }

    # Proxy admin Django
    location /admin/ {
        proxy_pass http://django:8000/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/javascript;
}
