# Generated by Django 6.0.2 on 2026-02-26 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_residence', models.CharField(max_length=200)),
                ('adresse_residence', models.TextField(blank=True)),
                ('ville_residence', models.CharField(blank=True, max_length=100)),
                ('code_postal_residence', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=50)),
                ('surface_lot', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('etage_lot', models.CharField(blank=True, max_length=50)),
                ('type_lot', models.CharField(blank=True, max_length=50)),
                ('remarque_lot', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='syndic.residence')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('residence', 'numero_lot'), name='uniq_lot_numero_par_residence')],
            },
        ),
        # migrations.CreateModel(
        #     name='ResidenceUser',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('role', models.CharField(choices=[('ADMIN', 'Admin résidence'), ('USER', 'Utilisateur')], default='USER', max_length=10)),
        #         ('is_active', models.BooleanField(default=True)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_memberships', to='syndic.residence')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences_memberships', to=settings.AUTH_USER_MODEL)),
        #     ],
        #     options={
        #         'constraints': [models.UniqueConstraint(fields=('user', 'residence'), name='uniq_user_par_residence')],
        #     },
        # ),
    ]
