# Generated by Django 6.0.2 on 2026-02-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='statut_lot',
            field=models.CharField(choices=[('A jour', 'A jour'), ('En retard', 'En retard'), ('Refus', 'Refus')], default='Disponible', max_length=20),
        ),
    ]
