# Generated by Django 6.0.2 on 2026-02-27 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0002_lot_statut_lot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residence',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='residence',
            name='classification',
            field=models.CharField(choices=[('PETITE', 'Petite'), ('MOYENNE', 'Moyenne'), ('GRANDE', 'Grande')], default='PETITE', max_length=10),
        ),
        migrations.AddField(
            model_name='residence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residence',
            name='statut_residence',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=10),
        ),
        migrations.AlterField(
            model_name='residence',
            name='adresse_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='code_postal_residence',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='nom_residence',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='residence',
            name='ville_residence',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='residence',
            unique_together={('nom_residence', 'ville_residence')},
        ),
        migrations.CreateModel(
            name='ResidenceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('GESTIONNAIRE', 'Gestionnaire'), ('COMPTABLE', 'Comptable'), ('LECTURE', 'Lecture seule')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='syndic.residence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residence_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['residence', 'user'],
                'unique_together': {('user', 'residence')},
            },
        ),
    ]
