# Generated by Django 6.0.2 on 2026-02-27 13:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0003_alter_residence_options_residence_classification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['residence', 'numero_lot']},
        ),
        migrations.AlterField(
            model_name='lot',
            name='statut_lot',
            field=models.CharField(choices=[('A_JOUR', 'A jour'), ('EN_RETARD', 'En retard'), ('REFUS', 'Refus')], db_index=True, default='A_JOUR', max_length=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='surface_lot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lot',
            name='type_lot',
            field=models.CharField(choices=[('APPARTEMENT', 'Appartement'), ('VILLA', 'Villa'), ('MAISON', 'Maison'), ('LOCAL', 'Local'), ('COMMERCE', 'Commerce'), ('BUREAU', 'Bureau'), ('AUTRE', 'Autre')], default='APPARTEMENT', max_length=20),
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_groupe', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='syndic.residence')),
            ],
            options={
                'ordering': ['residence', 'nom_groupe'],
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='syndic.groupe'),
        ),
        migrations.AddConstraint(
            model_name='groupe',
            constraint=models.UniqueConstraint(fields=('residence', 'nom_groupe'), name='uniq_groupe_nom_par_residence'),
        ),
    ]
