# Generated by Django 6.0.2 on 2026-02-27 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0004_alter_lot_options_alter_lot_statut_lot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(blank=True, max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('type_personne', models.CharField(choices=[('PHYSIQUE', 'Personne physique'), ('MORALE', 'Personne morale')], default='PHYSIQUE', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='occupant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_occupant', to='syndic.personne'),
        ),
        migrations.AddField(
            model_name='lot',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots_proprietaire', to='syndic.personne'),
        ),
        migrations.AddField(
            model_name='lot',
            name='representant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_representant', to='syndic.personne'),
        ),
    ]
