# Generated by Django 6.0.2 on 2026-02-27 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0005_personne_lot_occupant_lot_proprietaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnes', to='syndic.residence'),
        ),
    ]
