# Generated by Django 6.0.2 on 2026-03-01 15:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0006_personne_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='montant_ref',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='personne',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='residence',
            name='mode_appel_charge',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('ANNUEL', 'Annuel')], default='MENSUEL', max_length=10),
        ),
        migrations.CreateModel(
            name='AppelCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercice', models.IntegerField()),
                ('periode', models.CharField(max_length=7)),
                ('type_periode', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('ANNUEL', 'Annuel')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('NON_PAYE', 'Non payé'), ('PARTIEL', 'Partiel'), ('PAYE', 'Payé')], default='NON_PAYE', max_length=10)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels', to='syndic.lot')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels', to='syndic.residence')),
            ],
            options={
                'ordering': ['lot', 'periode'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='syndic.lot')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='syndic.residence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AffectationPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_affecte', models.DecimalField(decimal_places=2, max_digits=12)),
                ('appel_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='syndic.appelcharge')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='syndic.paiement')),
            ],
        ),
        migrations.AddConstraint(
            model_name='appelcharge',
            constraint=models.UniqueConstraint(fields=('lot', 'periode'), name='uniq_appel_par_lot_par_periode'),
        ),
        migrations.AlterUniqueTogether(
            name='affectationpaiement',
            unique_together={('paiement', 'appel_charge')},
        ),
    ]
