# Generated by Django 6.0.2 on 2026-03-01 16:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0007_lot_montant_ref_personne_cin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailAppelCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('NON_PAYE', 'Non payé'), ('PARTIEL', 'Partiel'), ('PAYE', 'Payé')], default='NON_PAYE', max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='appelcharge',
            options={'ordering': ['-exercice', 'periode']},
        ),
        migrations.RemoveConstraint(
            model_name='appelcharge',
            name='uniq_appel_par_lot_par_periode',
        ),
        migrations.AddField(
            model_name='appelcharge',
            name='date_eligibilite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appelcharge',
            name='date_emission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appelcharge',
            name='date_limite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appelcharge',
            name='type_appel',
            field=models.CharField(choices=[('CHARGE', 'Charge'), ('FOND', 'Fonds')], default='CHARGE', max_length=10),
        ),
        migrations.AlterField(
            model_name='appelcharge',
            name='exercice',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='appelcharge',
            name='periode',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='appelcharge',
            constraint=models.UniqueConstraint(fields=('exercice', 'periode'), name='uniq_exercice_periode'),
        ),
        migrations.AddField(
            model_name='detailappelcharge',
            name='appel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='syndic.appelcharge'),
        ),
        migrations.AddField(
            model_name='detailappelcharge',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_appels', to='syndic.lot'),
        ),
        migrations.RemoveField(
            model_name='appelcharge',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='appelcharge',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='appelcharge',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='appelcharge',
            name='type_periode',
        ),
        migrations.AddConstraint(
            model_name='detailappelcharge',
            constraint=models.UniqueConstraint(fields=('appel', 'lot'), name='uniq_lot_par_appel'),
        ),
    ]
