# Generated by Django 6.0.2 on 2026-03-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0008_detailappelcharge_alter_appelcharge_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appelcharge',
            name='type_appel',
        ),
        migrations.AddField(
            model_name='appelcharge',
            name='observation_appel',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appelcharge',
            name='type_charge',
            field=models.CharField(choices=[('ANNUEL', 'Charge Annuel'), ('MENSUEL', 'Charge Mensuel'), ('FOND', 'Appel de Fond')], default='ANNUEL', max_length=10),
        ),
        migrations.AlterField(
            model_name='appelcharge',
            name='periode',
            field=models.CharField(max_length=30),
        ),
    ]
