# Generated by Django 6.0.2 on 2026-03-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0009_remove_appelcharge_type_appel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appelcharge',
            old_name='observation_appel',
            new_name='description_appel',
        ),
        migrations.AlterField(
            model_name='appelcharge',
            name='periode',
            field=models.CharField(choices=[('ANNEE', 'Année'), ('JAN', 'Janvier'), ('FEV', 'Février'), ('MAR', 'Mars'), ('AVR', 'Avril'), ('MAI', 'Mai'), ('JUI', 'Juin'), ('JUL', 'Juillet'), ('AOU', 'Août'), ('SEP', 'Septembre'), ('OCT', 'Octobre'), ('NOV', 'Novembre'), ('DEC', 'Décembre')], default='JAN', max_length=30),
        ),
        migrations.AlterField(
            model_name='appelcharge',
            name='type_charge',
            field=models.CharField(choices=[('CHARGE', 'Appel de Charge'), ('FOND', 'Appel de Fond')], max_length=10),
        ),
    ]
