# Generated by Django 6.0.2 on 2026-03-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0010_rename_observation_appel_appelcharge_description_appel_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appelcharge',
            name='uniq_exercice_periode',
        ),
        migrations.AlterField(
            model_name='appelcharge',
            name='periode',
            field=models.CharField(default='JAN', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='appelcharge',
            constraint=models.UniqueConstraint(fields=('residence', 'exercice', 'periode'), name='uniq_exercice_periode_par_residence'),
        ),
    ]
