# Generated by Django 6.0.2 on 2026-03-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0011_remove_appelcharge_uniq_exercice_periode_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appelcharge',
            name='uniq_exercice_periode_par_residence',
        ),
        migrations.AddField(
            model_name='appelcharge',
            name='code_fond',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='appelcharge',
            name='periode',
            field=models.CharField(choices=[('ANNEE', 'Année'), ('JAN', 'Janvier'), ('FEV', 'Février'), ('MAR', 'Mars'), ('AVR', 'Avril'), ('MAI', 'Mai'), ('JUI', 'Juin'), ('JUL', 'Juillet'), ('AOU', 'Août'), ('SEP', 'Septembre'), ('OCT', 'Octobre'), ('NOV', 'Novembre'), ('DEC', 'Décembre'), ('FOND', 'Appel de Fond')], default='JAN', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='appelcharge',
            constraint=models.UniqueConstraint(condition=models.Q(('type_charge', 'CHARGE')), fields=('residence', 'exercice', 'periode'), name='uniq_charge_res_exo_periode'),
        ),
        migrations.AddConstraint(
            model_name='appelcharge',
            constraint=models.UniqueConstraint(condition=models.Q(('type_charge', 'FOND')), fields=('residence', 'exercice', 'code_fond'), name='uniq_fond_res_exo_code'),
        ),
    ]
