# Generated by Django 6.0.2 on 2026-03-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0012_remove_appelcharge_uniq_exercice_periode_par_residence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelcharge',
            name='nom_fond',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
