# Generated by Django 6.0.2 on 2026-03-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0013_appelcharge_nom_fond'),
    ]

    operations = [
        # 1️⃣ Supprimer l'ancien unique_together AVANT de toucher aux champs
        migrations.AlterUniqueTogether(
            name='affectationpaiement',
            unique_together=set(),
        ),

        # 2️⃣ Supprimer l'ancien champ
        migrations.RemoveField(
            model_name='affectationpaiement',
            name='appel_charge',
        ),

        # 3️⃣ Ajouter le nouveau champ
        migrations.AddField(
            model_name='affectationpaiement',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='syndic.detailappelcharge'),
        ),

        # 4️⃣ Remettre le unique_together avec le nouveau champ
        migrations.AlterUniqueTogether(
            name='affectationpaiement',
            unique_together={('paiement', 'detail')},
        ),
    ]