# Generated by Django 6.0.2 on 2026-03-03 22:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0014_alter_affectationpaiement_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailappelcharge',
            name='justificatif',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='detailappelcharge',
            name='montant_recu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='affectationpaiement',
            name='montant_affecte',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='detailappelcharge',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
