# Generated by Django 6.0.2 on 2026-03-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0015_detailappelcharge_justificatif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='residences/logos/'),
        ),
    ]
