# Generated by Django 6.0.2 on 2026-03-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0016_residence_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appelcharge',
            name='date_eligibilite',
        ),
        migrations.RemoveField(
            model_name='appelcharge',
            name='date_limite',
        ),
    ]
