# Generated by Django 6.0.2 on 2026-03-05 17:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0017_remove_appelcharge_date_eligibilite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appelcharge',
            name='periode',
            field=models.CharField(choices=[('ANNEE', 'Année'), ('JAN', 'Janvier'), ('FEV', 'Février'), ('MAR', 'Mars'), ('AVR', 'Avril'), ('MAI', 'Mai'), ('JUI', 'Juin'), ('JUL', 'Juillet'), ('AOU', 'Août'), ('SEP', 'Septembre'), ('OCT', 'Octobre'), ('NOV', 'Novembre'), ('DEC', 'Décembre'), ('FOND', 'Appel de fond')], default='JAN', max_length=30),
        ),
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('famille', models.CharField(choices=[('PERSONNEL', 'Personnel'), ('SECURITE', 'Sécurité'), ('NETTOYAGE', 'Nettoyage'), ('JARDINAGE', 'Jardinage'), ('ENERGIE', 'Énergie'), ('MAINTENANCE', 'Maintenance'), ('TRAVAUX', 'Travaux'), ('ADMIN', 'Administratif'), ('EQUIPEMENT', 'Équipement'), ('ANIMATION', 'Animation'), ('ASSURANCE_TAXE', 'Assurance & Taxes'), ('DIVERS', 'Divers')], default='DIVERS', max_length=20)),
                ('type_depense', models.CharField(choices=[('SYSTEMATIQUE', 'Systématique'), ('EVENTUELLE', 'Éventuelle')], default='EVENTUELLE', max_length=15)),
                ('nature', models.CharField(choices=[('FONCTIONNEMENT', 'Fonctionnement'), ('INVESTISSEMENT', 'Investissement')], default='FONCTIONNEMENT', max_length=15)),
                ('actif', models.BooleanField(default=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_depense', to='syndic.residence')),
            ],
            options={
                'ordering': ['famille', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('actif', models.BooleanField(default=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='syndic.residence')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_depense', models.DateField(default=django.utils.timezone.now)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('libelle', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('facture_reference', models.CharField(blank=True, max_length=100)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='depenses/justificatifs/')),
                ('commentaire', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='syndic.categoriedepense')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='syndic.residence')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='syndic.fournisseur')),
            ],
            options={
                'ordering': ['-date_depense', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoriedepense',
            constraint=models.UniqueConstraint(fields=('residence', 'nom'), name='uniq_categorie_nom_par_residence'),
        ),
        migrations.AddConstraint(
            model_name='fournisseur',
            constraint=models.UniqueConstraint(fields=('residence', 'nom'), name='uniq_fournisseur_nom_par_residence'),
        ),
    ]
