# Generated by Django 6.0.2 on 2026-03-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0018_depenses_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'M.'), ('Mme', 'Mme')], max_length=5),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='gsm',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='prenom',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
