# Generated by Django 6.0.2 on 2026-03-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0019_fournisseur_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='nom_societe',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom société'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='Nom contact'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='prenom',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prénom contact'),
        ),
    ]
