# Generated by Django 6.0.2 on 2026-03-06 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0025_comptecomptable_type_compte'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssembleeGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_ag', models.DateField()),
                ('type_ag', models.CharField(choices=[('ORDINAIRE', 'Ordinaire'), ('EXTRAORDINAIRE', 'Extraordinaire')], default='ORDINAIRE', max_length=20)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('TENUE', 'Tenue'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20)),
                ('ordre_du_jour', models.TextField(blank=True)),
                ('pv_document', models.FileField(blank=True, null=True, upload_to='gouvernance/pv/')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assemblees', to='syndic.residence')),
            ],
            options={
                'ordering': ['-date_ag'],
            },
        ),
        migrations.CreateModel(
            name='BureauSyndical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fonction', models.CharField(choices=[('PRESIDENT', 'Président'), ('VICE_PRESIDENT', 'Vice-Président'), ('TRESORIER', 'Trésorier'), ('SECRETAIRE', 'Secrétaire'), ('MEMBRE', 'Membre')], default='MEMBRE', max_length=30)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandats_bureau', to='syndic.personne')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureau_syndical', to='syndic.residence')),
            ],
            options={
                'ordering': ['residence', 'fonction'],
            },
        ),
        migrations.CreateModel(
            name='DocumentGouvernance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_document', models.CharField(choices=[('PV', 'Procès-verbal'), ('REGLEMENT', 'Règlement'), ('CONTRAT', 'Contrat'), ('RAPPORT', 'Rapport'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='gouvernance/documents/')),
                ('date', models.DateField()),
                ('visible_resident', models.BooleanField(default=False)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_gouvernance', to='syndic.residence')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('voix_pour', models.PositiveIntegerField(default=0)),
                ('voix_contre', models.PositiveIntegerField(default=0)),
                ('abstention', models.PositiveIntegerField(default=0)),
                ('resultat', models.CharField(choices=[('ADOPTEE', 'Adoptée'), ('REJETEE', 'Rejetée'), ('AJOURNEE', 'Ajournée')], default='ADOPTEE', max_length=20)),
                ('assemblee_generale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='syndic.assembleegenerale')),
            ],
            options={
                'ordering': ['assemblee_generale', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('assemblee_generale', 'numero'), name='uniq_resolution_numero_par_ag')],
            },
        ),
    ]
