# Generated by Django 6.0.2 on 2026-03-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0026_gouvernance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatBureauSyndical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('assemblee_generale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandats_bureau', to='syndic.assembleegenerale')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandats_bureau', to='syndic.residence')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='MandatBureauMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fonction', models.CharField(choices=[('PRESIDENT', 'Président'), ('VICE_PRESIDENT', 'Vice-Président'), ('TRESORIER', 'Trésorier'), ('SECRETAIRE', 'Secrétaire'), ('MEMBRE', 'Membre')], default='MEMBRE', max_length=30)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandats_membre', to='syndic.personne')),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='syndic.mandatbureausyndical')),
            ],
            options={
                'ordering': ['fonction'],
                'constraints': [models.UniqueConstraint(fields=('mandat', 'personne'), name='uniq_personne_par_mandat')],
            },
        ),
    ]
