# Generated by Django 6.0.2 on 2026-03-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0027_mandat_bureau'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='partage_rapport_resident',
            field=models.BooleanField(default=False, help_text='Partager le rapport financier avec les résidents'),
        ),
        migrations.AddField(
            model_name='residencemembership',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_memberships', to='syndic.lot'),
        ),
        migrations.AlterField(
            model_name='residencemembership',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('GESTIONNAIRE', 'Gestionnaire'), ('COMPTABLE', 'Comptable'), ('LECTURE', 'Lecture seule'), ('RESIDENT', 'Résident')], max_length=20),
        ),
    ]
