# Generated by Django 6.0.2 on 2026-03-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0029_residencemembership_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelcharge',
            name='date_refus',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appelcharge',
            name='date_retard',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appelcharge',
            name='periode',
            field=models.CharField(choices=[('ANNEE', 'Année'), ('JAN', 'Janvier'), ('FEV', 'Février'), ('MAR', 'Mars'), ('AVR', 'Avril'), ('MAI', 'Mai'), ('JUI', 'Juin'), ('JUL', 'Juillet'), ('AOU', 'Août'), ('SEP', 'Septembre'), ('OCT', 'Octobre'), ('NOV', 'Novembre'), ('DEC', 'Décembre'), ('FOND', 'Appel de fond')], default='ANNEE', max_length=30),
        ),
    ]
