# Generated by Django 6.0.2 on 2026-03-10 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0030_appel_charge_dates_retard_refus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appelcharge',
            name='date_refus',
        ),
        migrations.RemoveField(
            model_name='appelcharge',
            name='date_retard',
        ),
    ]
