# Generated by Django 6.0.2 on 2026-03-11 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0037_travaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivecomptable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='archivedepense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='archivepaiement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='archiverecette',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='travaux',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_notification', models.DateTimeField(auto_now_add=True)),
                ('type_notification', models.CharField(choices=[('SMS', 'SMS'), ('MESSAGE', 'Message'), ('SYSTEM', 'Système')], default='SMS', max_length=10)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('montant_du', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statut', models.CharField(choices=[('ENVOYE', 'Envoyé'), ('LU', 'Lu'), ('NON_LU', 'Non lu')], default='ENVOYE', max_length=10)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='syndic.lot')),
                ('personne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='syndic.personne')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='syndic.residence')),
            ],
            options={
                'ordering': ['-date_notification'],
            },
        ),
    ]
