# Generated by Django 6.0.2 on 2026-03-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0041_message_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelcharge',
            name='archive_comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_charges', to='syndic.archivecomptable'),
        ),
    ]
