# Generated by Django 6.0.2 on 2026-03-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0042_archive_appel_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travaux',
            name='statut',
            field=models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé'), ('INFORMATION', 'Information')], default='PLANIFIE', max_length=15),
        ),
    ]
