# Generated by Django 6.0.2 on 2026-03-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0043_travaux_statut_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
