# Generated by Django 6.0.2 on 2026-03-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0044_add_email_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='logo_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
