# Generated by Django 6.0.2 on 2026-03-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0045_add_logo_base64_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='email_password',
            field=models.CharField(blank=True, help_text="Mot de passe d'application SMTP pour l'envoi d'emails", max_length=255, null=True),
        ),
    ]
