# Generated by Django 6.0.2 on 2026-03-23 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0046_residence_email_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassationConsignes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_passation', models.DateField()),
                ('solde_caisse', models.DecimalField(decimal_places=2, default=0, help_text='Calculé automatiquement depuis la caisse', max_digits=14)),
                ('solde_banque', models.DecimalField(decimal_places=2, default=0, help_text='Solde compte bancaire saisi manuellement', max_digits=14)),
                ('justification_ecart', models.TextField(blank=True, help_text='Explication si solde caisse ≠ solde banque (ex: chèque non encaissé)')),
                ('notes', models.TextField(blank=True)),
                ('nom_syndic', models.CharField(blank=True, max_length=150)),
                ('nom_tresorier', models.CharField(blank=True, max_length=150)),
                ('assemblee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passation_consignes', to='syndic.assembleegenerale')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passations_consignes', to='syndic.residence')),
            ],
            options={
                'ordering': ['-date_passation'],
            },
        ),
        migrations.CreateModel(
            name='ReservePassation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, help_text='Montant associé si applicable', max_digits=12, null=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('passation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='syndic.passationconsignes')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
