# Generated by Django 6.0.2 on 2026-03-23 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0048_passation_signataires_entrants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intitule', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('type_vote', models.CharField(choices=[('MAJORITE_SIMPLE', 'Majorité simple (> 50 % des votants)'), ('MAJORITE_ABSOLUE', 'Majorité absolue (> 50 % des copropriétaires)'), ('DOUBLE_MAJORITE', 'Double majorité'), ('UNANIMITE', 'Unanimité')], default='MAJORITE_SIMPLE', max_length=30)),
                ('date_resolution', models.DateField()),
                ('date_debut_vote', models.DateTimeField(blank=True, null=True)),
                ('date_cloture_vote', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('EN_COURS', 'En cours de vote'), ('CLOTURE', 'Clôturé')], default='EN_PREPARATION', max_length=20)),
                ('assemblee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions_vote', to='syndic.assembleegenerale')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions_vote', to='syndic.residence')),
            ],
            options={
                'ordering': ['-date_resolution', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_vote', to='syndic.lot')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_vote', to='syndic.resolutionvote')),
            ],
            options={
                'ordering': ['lot__numero_lot'],
                'unique_together': {('resolution', 'lot')},
            },
        ),
        migrations.CreateModel(
            name='VoteResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choix', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('NEUTRE', 'Neutre')], max_length=10)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_resolution', to='syndic.lot')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='syndic.resolutionvote')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lot__numero_lot'],
                'unique_together': {('resolution', 'lot')},
            },
        ),
    ]
