# Generated by Django 6.0.2 on 2026-03-24 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0049_resolutions_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passationconsignes',
            name='date_passation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resolutionvote',
            name='assemblee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolutions_vote', to='syndic.assembleegenerale'),
        ),
    ]
