# Generated by Django 6.0.2 on 2026-03-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0052_aiconfig_global'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationvote',
            options={},
        ),
        migrations.AddField(
            model_name='assembleegenerale',
            name='convocation_envoyee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aidocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
