# Generated by Django 6.0.2 on 2026-03-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0053_convocation_envoyee_le'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelcharge',
            name='libelle',
            field=models.CharField(blank=True, help_text="Nom descriptif de l'appel (ex: Travaux ravalement 2026)", max_length=200),
        ),
    ]
