# Generated by Django 6.0.2 on 2026-03-27 19:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0054_appel_charge_libelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_contrat', models.CharField(choices=[('SECURITE', 'Sécurité'), ('ENTRETIEN', 'Entretien'), ('JARDINAGE', 'Jardinage'), ('EAU', 'Eau'), ('ELECTRICITE', 'Électricité'), ('ASCENSEUR', 'Ascenseur'), ('ASSURANCE', 'Assurance'), ('INTERNET', 'Internet / Télécom'), ('NETTOYAGE', 'Nettoyage'), ('AUTRE', 'Autre')], max_length=20)),
                ('libelle', models.CharField(help_text='Description du contrat', max_length=255)),
                ('periodicite', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('BIMESTRIEL', 'Bimestriel (2 mois)'), ('TRIMESTRIEL', 'Trimestriel (3 mois)'), ('SEMESTRIEL', 'Semestriel (6 mois)'), ('ANNUEL', 'Annuel')], default='MENSUEL', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('compte_comptable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='syndic.comptecomptable')),
                ('famille_depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='syndic.familledepense')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='syndic.fournisseur')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='syndic.residence')),
            ],
            options={
                'ordering': ['type_contrat', 'libelle'],
            },
        ),
    ]
