# Generated by Django 6.0.2 on 2026-03-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0055_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='reference_contrat',
            field=models.CharField(blank=True, help_text='Référence / numéro de contrat', max_length=100),
        ),
    ]
