# Generated by Django 6.0.2 on 2026-03-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0056_contrat_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
