# Generated by Django 6.0.2 on 2026-03-28 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0057_contrat_montant_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeledepense',
            options={'ordering': ['categorie__nom', 'nom']},
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='famille_depense',
        ),
        migrations.RemoveField(
            model_name='modeledepense',
            name='famille_depense',
        ),
        migrations.AddField(
            model_name='contrat',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrats_cat', to='syndic.categoriedepense'),
        ),
        migrations.AddField(
            model_name='modeledepense',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modeles_depense_cat', to='syndic.categoriedepense'),
        ),
    ]
