# Generated by Django 6.0.2 on 2026-04-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0062_suivi_lot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'ordering': ['nom_societe', 'nom']},
        ),
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('SECURITE', 'Sécurité'), ('ENTRETIEN', 'Entretien'), ('JARDINAGE', 'Jardinage'), ('EAU', 'Eau'), ('ELECTRICITE', 'Électricité'), ('ASCENSEUR', 'Ascenseur'), ('ASSURANCE', 'Assurance'), ('INTERNET', 'Internet / Télécom'), ('NETTOYAGE', 'Nettoyage'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='suivilot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
