# Generated by Django 6.0.2 on 2026-04-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0063_contrat_type_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailappelcharge',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
